### ISSUE TITLE
Can't use "drupal" driver

### ISSUE THREAD

**Issue by amitaibu** [jhedstrom/drupalextension#104]
On this configuration

``` yaml
default:
  suites:
    default:
      contexts:
        - Drupal\DrupalExtension\Context\DrupalContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
      base_url: 'http://localhost:9050/'
    Drupal\DrupalExtension:
      api_driver: 'drupal'
      drupal:
        drupal_root: "/var/www/my-site/www"
```

Upon `bin/behat -di` I get:

```
[InvalidArgumentException]            
Driver "blackbox" is not registered.
```

But I add the "blackbox"

``` yaml
    # ...
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drupal:
        drupal_root: "/var/www/my-site/www"
```

Upon `bin/behat -di` I get:

```
Fatal error: Class 'Behat\Behat\Context\BehatContext' not found in /.../behat/vendor/drupal/drupal-extension/doc/_static/snippets/beanslide.behat.inc on line 10
```
