### ISSUE TITLE
Problem with Drupal driver in version 3.0

### ISSUE THREAD

**Issue by jurgenhaas** [jhedstrom/drupalextension#108]
When I want to use the Drupal driver as documented in version 3.0, then Behat doesn't find any test anymore. My behat.yml looks like this:

```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
      base_url: http://localhost/
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: "drupal"
      drupal:
        drupal_root: "/var/www/t/crm/htdocs"
      subcontexts:
        paths:
          - "/path/to/my/subcontexts"
```

When I call Behat with that, just nothing happens. When I then remove drupal.drupal_root from the yml file, then behat runs my tests but the drupal driver is not loaded then and hence I can't use the subcontext either.

I did some debugging and when drupal_drupal_root is defined then \Drupal\Driver\DrupalDriver gets initiated and it finds the correct Drupal version. But it doesn't run any tests without any error messages.

What am I doing wrong?
