### ISSUE TITLE
Problem with context namespacing

### ISSUE THREAD

**Issue by dutchiexl** [jhedstrom/drupalextension#122]
I added this to my main composer file:
```
 "autoload": {
    "psr-0": {
      "Emuse": "emuse/"
    }
  }
```

I added a folder emuse in my root and created a Context file: 
```
namespace Emuse;

class EmuseContext extends DrupalContext {}
```

When I set behat to use this context it says it cannot be found, although when I look in my composer namespace files, everything seems to be ok:

```
suites:
    default:
      contexts:
        - Emuse\EmuseContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
```
