### ISSUE TITLE
Can't get it working in Behat 3

### ISSUE THREAD

**Issue by kevinquillen** [jhedstrom/drupalextension#130]
I was able to get this working last year under Behat 2, but just did a fresh install, and cannot get it to work. I feel like I cannot get the driver to find my local site.

Here is my composer.json:

```
{
  "name": "test/test",
  "description": "drupal7",
  "require": {
    "drupal/drupal-extension": "~3.0"
  }
}
```

Here is my behat.yml:

```
default:
   suites:
     default:
       contexts:
         - FeatureContext
         - Drupal\DrupalExtension\Context\RawDrupalContext
         - Drupal\DrupalExtension\Context\DrupalContext
         - Drupal\DrupalExtension\Context\MinkContext
       extensions:
           Behat\MinkExtension:
             goutte: ~
             javascript_session: selenium2
             selenium2:
               wd_host: http://local.d7sandbox.com:8643/wd/hub
             base_url: http://local.d7sandbox.com
           Drupal\DrupalExtension:
             blackbox: ~
             api_driver: 'drupal'
             drupal:
               drupal_root: '/var/www/site/docroot'
```

Here is my feature context:

```
<?php

use Behat\Behat\Tester\Exception\PendingException;
use Drupal\DrupalExtension\Context\RawDrupalContext;
use Behat\Behat\Context\Context;
use Behat\Behat\Context\SnippetAcceptingContext;
use Behat\Gherkin\Node\PyStringNode;
use Behat\Gherkin\Node\TableNode;

/**
 * Defines application features from the specific context.
 */
class FeatureContext implements Context, SnippetAcceptingContext
{
    /**
     * Initializes context.
     *
     * Every scenario gets its own context instance.
     * You can also pass arbitrary arguments to the
     * context constructor through behat.yml.
     */
    public function __construct()
    {
    }
}
```

I can see the custom step definitions with bin/behat -di. Here is the output when I try a simple scenario:

```
Feature: Content Management
  When I log into the website
  As an administrator
  I should be able to create, edit, and delete page content

  Scenario: An administrative user should be able create page content
    Given I am logged in as a user with the "administrator" role
    When I go to "node/add/page"
    Then I should not see "Access denied"
```

Here is the error output:

```
Feature: Content Management
  When I log into the website
  As an administrator
  I should be able to create, edit, and delete page content

  Scenario: An administrative user should be able create page content # features/test.feature:6
PHP Fatal error:  Call to a member function getSession() on a non-object in /Users/kevinquillen/Sites/drupal7/vendor/behat/mink-extension/src/Behat/MinkExtension/Context/RawMinkContext.php on line 101
```

I feel like I have ran into this before with a similar error a while ago but don't recall how I fixed it.

Does vendor and behat features need to reside outside of the Drupal docroot? I currently have them within. I am not sure where I messed up, but I feel like I am very close I just cannot communicate with the virtualized site in Vagrant.

**Comment by kevinquillen** [comment]
Typo in step

**Comment by kevinquillen** [comment]
Actually.. when I remove the behat.yml, I get a different error about it not able to find the step definitions. Placing it back, I get the 'getSession' error. This seems to be a common error with Mink, but I can't see where I have gone wrong. 'features' folder is in the Drupal docroot, as is behat.yml, and vendor/ folder with composer packages.

**Comment by kevinquillen** [comment]
Update on this... when I fall back to the 1.0 version following my own setup guide, it works fine:

http://kevinquillen.com/bdd/2014/06/06/behat-drupal/

Following the given documentation for 3.0, I get the 'getSession' error.

**Comment by eliza411** [comment]
Which page of documentation were you following? As far as I can see the README, standalone and site-wide docs all have the proper indentation in the behat.yml file, but your example has an indentation error.

```
default:
   suites:
     default:
       contexts:
         - FeatureContext
         - Drupal\DrupalExtension\Context\RawDrupalContext
         - Drupal\DrupalExtension\Context\DrupalContext
         - Drupal\DrupalExtension\Context\MinkContext
       extensions:
           Behat\MinkExtension:
             goutte: ~
             javascript_session: selenium2
             selenium2:
               wd_host: http://local.d7sandbox.com:8643/wd/hub
             base_url: http://local.d7sandbox.com
           Drupal\DrupalExtension:
             blackbox: ~
             api_driver: 'drupal'
             drupal:
               drupal_root: '/var/www/site/docroot'
```
The extensions stanza should line up with the first indentation level (suites:) rather than the third (contexts:) 

Try the following:
```
default:
   suites:
     default:
       contexts:
         - FeatureContext
         - Drupal\DrupalExtension\Context\RawDrupalContext
         - Drupal\DrupalExtension\Context\DrupalContext
         - Drupal\DrupalExtension\Context\MinkContext
   extensions:
       Behat\MinkExtension:
         goutte: ~
         javascript_session: selenium2
         selenium2:
           wd_host: http://local.d7sandbox.com:8643/wd/hub
         base_url: http://local.d7sandbox.com
       Drupal\DrupalExtension:
         blackbox: ~
         api_driver: 'drupal'
         drupal:
           drupal_root: '/var/www/site/docroot'
```
Indented like the docs examples, everything runs fine. Indented as it is in the first example, I get the same error you do.

I'll be happy to update the errant docs out there if you can point me toward them.
