### ISSUE TITLE
Logged in as user role not working as expected, doesn't function properly when used in conjunction with FeatureContext

### ISSUE THREAD

**Issue by lpeabody** [jhedstrom/drupalextension#167]
It appears as if the step definition **I am logged in as a user with the :role role(s)** doesn't completely work in a scenario that includes steps defined in FeatureContext.php. To be specific, if a user is logged in via this step, and then you invoke a custom step definition afterwards that depends on a user being logged in with a particular role, then that step will fail.

This is how FeatureContext is defined:
`class FeatureContext extends DrupalContext {`

And I have the following step definition for the FeatureContext class:

```
  /**
   * @When I go to the :type add form
   * @When I am creating a/an :type
   * @Then I should be able to create a :type( content)
   */
  public function iGoToTheAddForm($type)
  {
    $types = node_type_get_types();
    foreach ($types as $node_type) {
      if ($type == $node_type->name) {
        $type = $node_type->type;
        break;
      }
    }

    $this->visitPath('/node/add/' . str_replace('_', '-', $type));
    $this->assertSession()->statusCodeEquals('200');
  }
```

And also the following scenario:

```
  Scenario: When creating an event, a client can select a layout
    Given I am logged in as a user with the "Client Admin" role
    And I am viewing my "Event" with the title "Example Client Event"
    When I go to the "Event" add form
```

Assume the role *Client Admin* has permission to create a node of type Event. The step `When I go to the "Event" add form` fails, and reports back a 403 instead of a 200 like it should. This is surprising to me since the step **And I am viewing my "Event" with the title "Example Client Event"** passes, but requires the exact same permission set as **When I go to the "Event" add form**.

When I place a breakpoint in ```assertAuthenticatedByRole``` in **DrupalContext** and check the properties of ```$this``` after ```$this->login();```, I can see the properties ```$user``` and ```$users``` are set. Having also set a breakpoint in ```iGoToTheAddForm``` in **FeatureContext**, the properties ```$user``` and ```$users``` are not set, but I would expect they would be because of the prior invocation of ```assertAuthenticatedByRole```.

Am I mistaken in thinking that the ```$user``` and ```$users``` properties should be set? I think this is probably a bug within DrupalExtension, but I'm hoping that's not the case and someone here can point out I'm doing something incorrectly.

Including behat.yml also:

```
default:
  suites:
    default:
      contexts:
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - FeatureContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
      base_url: http://foto.dev/
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drush:
        alias: 'local.foto'
      drupal:
        drupal_root: '/Users/scrubbed/Sites/foto-opp/docroot'
```
