### ISSUE TITLE
Travis build failing on PHP 5.4

### ISSUE THREAD

**Issue by pfrenssen** [jhedstrom/drupalextension#186]
Since Drupal 8 is now requiring PHP 5.5, the Travis build fails for PHP 5.4:

```
Your PHP installation is too old. Drupal requires at least PHP <em class="placeholder">5.5.9</em>.
```

I did some experimentation the other day and we cannot run the tests on PHP 5.6 or PHP 7 because it is impossible to install Drupal 6 on those. This is most likely due to a configuration problem on the Travis test servers since I was able to install Drupal 6 without problems on my local dev machine with PHP 5.6

So we are currently in the awkward position that the tests only pass on a very narrow band of available versions: PHP 5.5 or naught :)

Would a good solution be to start using a full build matrix that captures the allowed versions for each? Something like this perhaps:

```
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
env:
  - DRUPAL_VERSION=6
  - DRUPAL_VERSION=7
  - DRUPAL_VERSION=8

matrix:
  exclude:
    - php: 5.4
      env: DRUPAL_VERSION=8
    - php: 5.6
      env: DRUPAL_VERSION=6
    - php: 7.0
      env: DRUPAL_VERSION=6
```
