### ISSUE TITLE
Unable to list definitions

### ISSUE THREAD

**Issue by mortona42** [jhedstrom/drupalextension#226]
I followed the steps in the full documentation, and when I run [bin/behat -di (or -dl)], nothing is listed.

**Comment by jhedstrom** [comment]
What happens if you add `--verbose`? Anything different? Could you post a copy of your `behat.yml` here?

**Comment by mortona42** [comment]
Adding --verbose still gives empty output.

For behat.xml I tried with the samples in the full documentation and in this repo's readme:

```yaml
default:
  suites:
    default:
      contexts:
        - Drupal\DrupalExtension\Context\DrupalContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      base_url: http://localhost:80
    Drupal\DrupalExtension:
      blackbox: ~
```

Thanks for your response!

**Comment by kevinquillen** [comment]
I am having the same issue, a little different though.

If I do vendor/bin/behat -c behat.yml -dl, I see all the definitions.

When I execute Behat in command line or from PHPStorm, it claims the step I am using is missing. How can that be if I am executing it with the -c behat.yml (which is default anyway)? How is it unaware of the steps?

```
--- FeatureContext has missing steps. Define them with these snippets:

    /**
     * @When I go to :arg1
     */
    public function iGoTo($arg1)
    {
        throw new PendingException();
    }
```

Config:

```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
      base_url: http://local.d8contrib
    Drupal\DrupalExtension:
      api_driver: 'drupal'
      blackbox: ~
      drupal:
        drupal_root: '/var/www/docroot'
```

FeatureContext.php:

```
<?php

use Drupal\DrupalExtension\Context\RawDrupalContext;
use Behat\Behat\Context\SnippetAcceptingContext;
use Behat\Gherkin\Node\PyStringNode;
use Behat\Gherkin\Node\TableNode;

/**
 * Defines application features from the specific context.
 */
class FeatureContext extends RawDrupalContext implements SnippetAcceptingContext {

  /**
   * Initializes context.
   *
   * Every scenario gets its own context instance.
   * You can also pass arbitrary arguments to the
   * context constructor through behat.yml.
   */
  public function __construct() {
  }

}
```

I am also trying to run just a very basic test against D8, when a user visits the homepage.
