### ISSUE TITLE
Which version?

### ISSUE THREAD

**Issue by aaronbauman** [jhedstrom/drupalextension#228]
Docs say to use ~3.0
But i'm getting an SSL Cert error because of missing options and outdated dependencies without 3.1

Specifically, DE's Mink version relies on an ancient version of Guzzle, about which composer is throwing errors. 
Additionally, I have errors on local dev when trying to test over https with a fake cert (expected), but i'm missing the option to tell goutte to ignore them (because of the older versions. see https://github.com/Behat/MinkExtension/issues/47 for background there.)

How do i know which version to use?

**Comment by jhedstrom** [comment]
Specifying `~3.0` should pull the latest `3.1` version. If for some reason it isn't, you can also specify exact versions, or `3.1.*` would ensure that the latest 3.1 is used.

See https://getcomposer.org/doc/articles/versions.md#tilde

**Comment by aaronbauman** [comment]
I followed (the docs)[https://behat-drupal-extension.readthedocs.org/] that said "~3.0" and wound up with the issues described above.
I changed to "3.*" and got a bunch of updates.

Is there any reason to prefer the 3.0 branch over 3.1?
Should I make a pull request against those docs to use 3.1.* instead?

**Comment by jhedstrom** [comment]
You could add a PR to update to `~3.1`, but I wouldn't want to tell folks to pin themselves on `3.1`. The `~` means they'll get everything less than `4.0`.

What errors are you getting? As mentioned, `~3.0` *should* be pulling the very latest `3.1` release.

**Comment by aaronbauman** [comment]
OK, well now i'm unable to reproduce this.
Using ~3.0 is giving me 3.1.2 now, and the errors went away.
Maybe i just needed a composer update?

[Here's a dump](https://gist.github.com/aaronbauman/3d4fdebb067a0cc72166) of the behat output i was getting.
Since i'm testing locally, I don't have a valid cert.
I tracked this down to https://github.com/Behat/MinkExtension/issues/47 and updated my behat.yml to look like this:
```
    Behat\MinkExtension:
      goutte:
        guzzle_parameters:
          verify: false
          curl.options:
            CURLOPT_SSL_VERIFYPEER: false
            CURLOPT_CERTINFO: false
            CURLOPT_TIMEOUT: 120
          ssl.certificate_authority: false
```

Then, running behat again, same output.
Guzzle was ignoring all the additional params.
Now it's working fine.

I'm still getting "Package guzzle/* is abandoned" errors, but i'll file a separate issue for that.
