### ISSUE TITLE
Test failed on "Given I am logged" definition

### ISSUE THREAD

**Issue by geraldvillorente** [jhedstrom/drupalextension#250]
Behat newbie here. I am running Drupal 8 with Behat 3 and Zombie. I am testing the basic of Behat and I came across on testing user roles. 

My feature:

```
Feature: DrupalContext
  In order to prove the Drupal context is working properly for Drupal 8
  As a developer
  I need to use the step definitions of this context

  Scenario: Create and log in as a user
    Given I am logged in as a user with the "authenticated user" role
    When I click "My account"
    Then I should see the text "Member for"
```

Error:

```
$ bin/behat --stop-on-failure features/login/login.feature 
@api
Feature: DrupalContext
  In order to prove the Drupal context is working properly for Drupal 8
  As a developer
  I need to use the step definitions of this context

  Scenario: Create and log in as a user                               # features/login/login.feature:7
    Given I am logged in as a user with the "authenticated user" role # Drupal\DrupalExtension\Context\DrupalContext::assertAuthenticatedByRole()
      Server process has been terminated: (1) [node_modules/jsdom/lib/jsdom/living/node-iterator.js:3
      const defineGetter = require("../utils").defineGetter;
      ^^^^^
      SyntaxError: Use of const in strict mode.
          at exports.runInThisContext (vm.js:73:16)
          at Module._compile (module.js:443:25)
          at Object.Module._extensions..js (module.js:478:10)
          at Module.load (module.js:355:32)
          at Function.Module._load (module.js:310:12)
          at Module.require (module.js:365:17)
          at require (module.js:384:17)
          at Object.<anonymous> (node_modules/jsdom/lib/jsdom/living/index.js:22:1)
          at Module._compile (module.js:460:26)
          at Object.Module._extensions..js (module.js:478:10)
          at Module.load (module.js:355:32)
          at Function.Module._load (module.js:310:12)
          at Module.require (module.js:365:17)
          at require (module.js:384:17)
          at Object.<anonymous> (node_modules/zombie/lib/dom/index.js:5:11)
          at Module._compile (module.js:460:26)
      ] (RuntimeException)
    When I click "My account"                                         # Drupal\DrupalExtension\Context\MinkContext::assertClick()
    Then I should see the text "Member for"                           # Drupal\DrupalExtension\Context\MinkContext::assertTextVisible()

--- Failed scenarios:

    features/login/login.feature:7

1 scenario (1 failed)
3 steps (1 failed, 2 skipped)
0m1.85s (27.13Mb)
```

behat.yml:

```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
      zombie: ~
      base_url: http://local.drupal8-api.dev
      default_session: 'zombie'
      javascript_session: zombie
      zombie:
        node_modules_path: /home/gerald/Repo/d8-api-test/tests/node_modules/
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drush:
        alias: 'd8.local'
      drupal:
        drupal_root: '/home/gerald/Repo/d8-api-test/app'
      subcontexts:
        paths:
          - '/home/gerald/Repo/d8-api-test/app/modules'
```

```
gerald@von-viel ~/Repo/d8-api-test/tests/node_modules (master *>) $ tree -L 1
.
├── behat.yml
├── behat.yml.default
├── bin
├── composer.json
├── composer.lock
├── composer.phar
├── features
├── node_modules
└── vendor

gerald@von-viel ~/Repo/d8-api-test/tests/node_modules (master *>) $ tree -L 1
.
├── acorn
├── acorn-globals
├── amdefine
├── ansi-regex
├── ansi-styles
├── asn1
├── assert-plus
├── async
├── aws4
├── aws-sign2
├── babel-runtime
├── bindings
├── bl
├── bluebird
├── boom
├── browser-request
├── bufferutil
├── caseless
├── chalk
├── combined-stream
├── commander
├── core-js
├── core-util-is
├── cryptiles
├── cssom
├── cssstyle
├── dashdash
├── debug
├── deep-is
├── delayed-stream
├── domelementtype
├── domhandler
├── dom-serializer
├── domutils
├── ecc-jsbn
├── entities
├── escape-string-regexp
├── escodegen
├── esprima
├── estraverse
├── esutils
├── eventsource
├── extend
├── extsprintf
├── fast-levenshtein
├── forever-agent
├── form-data
├── generate-function
├── generate-object-property
├── graceful-readlink
├── har-validator
├── has-ansi
├── hawk
├── hoek
├── htmlparser2
├── http-signature
├── iconv-lite
├── inherits
├── isarray
├── is-my-json-valid
├── is-property
├── isstream
├── is-typedarray
├── jodid25519
├── jsbn
├── jsdom
├── jsonpointer
├── json-schema
├── json-stringify-safe
├── jsprim
├── levn
├── lodash
├── lru-cache
├── mime
├── mime-db
├── mime-types
├── ms
├── nan
├── node-uuid
├── nwmatcher
├── oauth-sign
├── optionator
├── options
├── original
├── parse5
├── pinkie
├── pinkie-promise
├── prelude-ls
├── process-nextick-args
├── punycode
├── qs
├── querystringify
├── readable-stream
├── request
├── requires-port
├── sntp
├── source-map
├── sshpk
├── string_decoder
├── stringstream
├── strip-ansi
├── supports-color
├── tough-cookie
├── tunnel-agent
├── tweetnacl
├── type-check
├── ultron
├── url-parse
├── utf-8-validate
├── util-deprecate
├── verror
├── wordwrap
├── ws
├── xmlhttprequest
├── xml-name-validator
├── xtend
└── zombie

117 directories, 0 files
```
