### ISSUE TITLE
Runtime Exception:  sh: 1:  drush: not found

### ISSUE THREAD

**Issue by lhridley** [jhedstrom/drupalextension#384]
I'm trying to write some behat tests to check the output of some drush commands, and I keep getting a Runtime Exception error.

I am using a docker stack, which has worked just fine for executing scenarios that are browser driven using a Selenium container running either Firefox or Chrome, and I've also executed scenarios that run commands using the Drupal API driver without issue.

I'm running into the Runtime Exception error when trying to execute any Scenarios that involve drush command steps.

My (partial) configuration is as follows (I have a separate composer file for the test stack, the site is D7 installed in a traditional manner without composer):

composer:
```
{
    "config": {
        "secure-http": false,
        "discard-changes": true,
        "bin-dir": "bin/"
    },
    "conflict": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "composer/composer": "1.3",
        "guzzlehttp/guzzle" : "^6.0@dev",
        "drupal/drupal-extension": "*",
        "drupal/drupal-driver": "*",
        "lakion/mink-debug-extension": "dev-master",
        "behat/behat": "3.3",
        "behat/mink": "~1.7",
        "behat/mink-goutte-driver": "~1.2",
        "mikey179/vfsStream": "~1.2",
        "symfony/css-selector": "~3.1",
        "drupal/coder": "~7.2.5",
        "drush/drush": "7.*",
        "phpunit/phpunit": "*",
        "phpunit/php-invoker": "*",
        "phpunit/dbunit": "*",
        "fabpot/goutte": "*"
    }
}

```

behat.yml (partial):
```
default:
  suites:
    default:
      paths:
        - %paths.base%/features/default
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\MinkContext
...
    drush:
      paths:
        - %paths.base%/features/drush
      contexts:
        - DrushOutputContext <== (this Context extends Drupal]DrupalExtension\Context\DrushContext)
        - Drupal\DrupalExtension\Context\MinkContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2:
        browser: 'firefox'
        wd_host: 'selenium:4444/wd/hub'
      base_url: 'http://nginx' <== (name of web container in the docker-compose.yml file, tests are executed in the PHP container, which runs php-fpm)
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drush' <== I've used 'drush' and 'drupal' with the same results
      drupal:
        drupal_root: '/var/www/html/docroot'
      drush:
        alias: 'default.dev'
        root: '/var/www/html/docroot'
      region_map:
...

```

Behat Feature:

```
Feature:  Checking state of features

  @api
  Scenario: Check that features states are expected
    Given I run drush "features-list" "--format=yaml" <== Steps are failing here
    Then drush output should contain: <== This step is skipped due to previous step failing
"""
... (multline output)
"""

```

I have a drush alias file defined and available in the php container, as follows:
```
<?php
$aliases[isset($_SERVER['PHP_SITE_NAME']) ? $_SERVER['PHP_SITE_NAME'] : 'dev'] = [
  'root' => '/var/www/html/' . (isset($_SERVER['PHP_DOCROOT']) ? $_SERVER['PHP_DOCROOT'] : ''),
  'uri' => isset($_SERVER['PHP_HOST_NAME']) ? $_SERVER['PHP_HOST_NAME'] : 'localhost:8080',
];
```

And my Test output is:

```
Feature: Checking state of features

  @api
  Scenario: Check that features states are expected   # features/drush/features-check.feature:4
    Given I run drush "features-list" "--format=yaml" # DrushOutputContext::assertDrushCommandWithArgument()
      sh: 1: drush: not found
       (RuntimeException)
...
```

I'm failing to see what I have misconfigured, and why drush cannot be found.  The executable is available in the vendor/bin/ directory.

Any assistance or guidance would be most appreciated.
