### ISSUE TITLE
How to change/set ajax_timeout

### ISSUE THREAD

**Issue by miiimooo** [jhedstrom/drupalextension#486]
I have found a problem that click/select steps don't wait long enough (or at all?)

Trying to debug it I got this output:
```
│
    ╳  Unable to complete AJAX request. {"name":"step.after","feature":"Terms","step":"I click the text \"Jag vill vara anonym\"","suite":"default","ajax_timeout":null} (RuntimeException)
```
You see I have added some debugging code to display the ajax_timeout. 
The reference in master is here https://github.com/jhedstrom/drupalextension/blob/master/src/Drupal/DrupalExtension/Context/MinkContext.php#L153

I can't work out where to set this. I tried in behat.yml 
```
  extensions:
    Behat\MinkExtension:
      ajax_timeout: 5
```
I got 
```
    In ArrayNode.php line 311:
                                                                                         
  Unrecognized option "ajax_timeout" under "testwork.mink"  
```

**Comment by jhedstrom** [comment]
Since the `ajax_timeout` parameter is provided by this extension, you need to update your extension section to specify `Drupal\MinkExtension` rather than `Behat\MinkExtension`:

```yaml
  extensions:
    Drupal\MinkExtension:
      ajax_timeout: 5
```
Note that `5` is the default behavior, so you may want to try `10` or `15`.

**Comment by miiimooo** [comment]
Thanks @jhedstrom 

Did you notice the error output above? It seems like the default was null there

**Comment by miiimooo** [comment]
I can see a default of 5 in vendor/drupal/drupal-extension/src/Drupal/MinkExtension/ServiceContainer/MinkExtension.php but I don't think that is used in this context

I have vendor/behat/mink-extension/src/Behat/MinkExtension/Context/RawMinkContext.php which provides the public function getMinkParameter($name) which is used by vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/MinkContext.php:iWaitForAjaxToFinish

**Comment by miiimooo** [comment]
Found I had version spaghetti

**Comment by jhedstrom** [comment]
Glad you got it working :)

**Comment by miiimooo** [comment]
I realise this is still happening, independent of behat version.

Could someone confirm that in vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/MinkContext.php:153 they actually get a value for $this->getMinkParameter('ajax_timeout')? 

I only get NULL and hence a "Unable to complete AJAX request. {"name":"step.after","feature":"XXXXXXXX","step":"XXXXXXXXXXXXX","suite":"default"} (RuntimeException)

When I set the ajax_timeout as you wrote then the first step in my scenario never runs and just sits there and waits.

**Comment by arosboro** [comment]
@miimoo Are you using the Drupal API driver or the drush driver?

**Comment by arosboro** [comment]
It looks like this is due to using drush without a selenium2 browser, I switched back to configuring selenium2 with chrome, and made sure chrome was running as instructed here: https://packagist.org/packages/dmore/chrome-mink-driver and the behat features requiring javascript worked as usual.

**Comment by leevh** [comment]
I *think* some confusion here comes from it sounds like you only need to follow the instructions in https://github.com/jhedstrom/drupalextension/issues/486#issuecomment-385461668 if you want to specify a custom timeout.  But if you don't use Drupal\MinkExtension rather than Behat\MinkExtension in your behat.yml, you will not have the timeout variable at all, and iWaitForAjaxToFinish depends on it being set.  Seems like maybe the documentation should change to use only Drupal\MinkExtension, or iWaitForAjaxToFinish should provide a default if one is not present.

**Comment by pfrenssen** [comment]
Yes this is a very good point @leevh. In fact one of my team members got hit this week with exactly the same problem as you describe.

I propose we do a check and if the value of `ajax_timeout` is `NULL` then we throw an exception which explains that `Drupal\MinkExtension` should be used. This will clear up a lot of confusion I think.

**Comment by miiimooo** [comment]
Thanks @leevh and @pfrenssen . That was exactly the problem! We've changed this in a number of projects now and the problem is gone

**Comment by stevenlafl** [comment]
> Since the `ajax_timeout` parameter is provided by this extension, you need to update your extension section to specify `Drupal\MinkExtension` rather than `Behat\MinkExtension`:
> 
> ```yaml
>   extensions:
>     Drupal\MinkExtension:
>       ajax_timeout: 5
> ```
> 
> Note that `5` is the default behavior, so you may want to try `10` or `15`.

 `Drupal\MinkExtension` extension file or class could not be located.

However, when using `Drupal\DrupalExtension`, I get:
Unrecognized option "ajax_timeout" under "testwork.drupal"

So where is it? I'm using `"drupal/drupal-extension": "~3.0",`

**Comment by brooke-heaton** [comment]
I'm equally confused by all of the above. I get the same error as @stevenlafl

**Comment by jhedstrom** [comment]
The `Drupal\MinkExtension` class was introduced only in version 4 of this library, so if you're running 3 or older, you will get the class not found error I think.

**Comment by grasmash** [comment]
I found this a bit tricky. To get it working, I had to split some configuration between Drupal\MinkExtension and Behat\MinkExtension:

```
    Drupal\MinkExtension:
      ajax_timeout: 5
      browser_name: chrome
      javascript_session: default
      # configure the base url for your site
      base_url: http://local.guitargate.com
      # set default command for "Show last response" step.
      show_cmd: "open %s"
    Behat\MinkExtension:
      base_url: http://local.guitargate.com
      sessions:
        default:
          chrome:
            api_url: "http://localhost:9222"
            # Set the optimal Socket Timeout to avoid client-server connection problems in behat scripts.
            socket_timeout: 60
```
