### ISSUE TITLE
Log in when current language different from English

### ISSUE THREAD

**Issue by leymannx** [jhedstrom/drupalextension#524]
v3.4.1. – I have a French site here. Actually it's just language negotiation set to use Domain instead of path prefixes. And I have an `edit.feature` with a scenario that just ensures certain roles can log in and edit random nodes:

```
Feature: Let's login as users with certain roles and check that node edit
  forms are accessible.

  @api
  Scenario: Login as publisher and try to edit some random node forms
    Given I am logged in as a publisher
    # ...
```

Logging in using the English base URL `english-site.localhost` works just fine. But running the same test against the French base URL `frensh-site.localhost` gives me following error:

>     Given I am logged in as a publisher                               # Drupal\DrupalExtension\Context\DrupalContext::assertAuthenticatedByRole()
>       Form field with id|name|label|value|placeholder "Password" not found. (Behat\Mink\Exception\ElementNotFoundException)

I then might have found the culprit here:

https://github.com/jhedstrom/drupalextension/blob/50ff0f413f0dc4732f49638e743f86f45e835e50/src/Drupal/DrupalExtension/Context/RawDrupalContext.php#L550-L552

When I change the above to use the `name` attributes of the input elements and the translated "Log in" string it starts working again.

    $element->fillField('name', $user->name);
    $element->fillField('pass', $user->pass);
    $submit = $element->find('xpath', '//form[@id="user-login-form"]')->find('xpath', '//input[@type="submit"]');

Do we need to fix this? Or is there already some `getTranslationFromContext` kind of functionality implemented at some place and I only need to define a `default_language` or something like that in my `behat.yml`?

Refs #93

**Comment by leymannx** [comment]
```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\BigPipeContext
        - IntegratedExperts\BehatScreenshotExtension\Context\ScreenshotContext
        - MOrtola\BehatSEOContexts\MetaContext
        - MOrtola\BehatSEOContexts\LocalizationContext
        - MOrtola\BehatSEOContexts\RobotsContext
        - MOrtola\BehatSEOContexts\RedirectContext
        - MOrtola\BehatSEOContexts\SitemapContext
        - MOrtola\BehatSEOContexts\HTMLContext
        - MOrtola\BehatSEOContexts\PerformanceContext
        - MOrtola\BehatSEOContexts\SocialContext
  extensions:
    Behat\MinkExtension:
      base_url: http://french-site.localhost
      goutte: ~
      selenium2:
        wd_host: http:/french-site.localhost:4444/wd/hub
        capabilities:
          marionette: true
          browser: chrome
      browser_name: chrome
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: drupal
      drupal:
        drupal_root: %paths.base%/../../web
    Bex\Behat\ScreenshotExtension:
      screenshot_taking_mode: failed_steps
      image_drivers:
        local:
          screenshot_directory: ../tests/behat/screenshots/failed_steps/chrome
    IntegratedExperts\BehatScreenshotExtension:
      dir: %paths.base%/screenshots/chrome
      fail: true
      purge: false
```

**Comment by jonathanjfshaw** [comment]
Unfortunately it's not always easy to find things in the docs:
https://behat-drupal-extension.readthedocs.io/en/3.1/blackbox.html

```
Drupal\DrupalExtension:
  text:
    log_out: "Sign out"
    log_in: "Sign in"
    password_field: "Enter your password"
    username_field: "Nickname"
```
