### ISSUE TITLE
File uploads are failing with Javascript error

### ISSUE THREAD

**Issue by ptmkenny** [jhedstrom/drupalextension#574]
In my test to upload an audio file, I'm getting the following AJAX error.

```
    And I attach the file "myfile.mp3" to "Add a new file" # Drupal\DrupalExtension\Context\MinkContext::attachFileToField()
    ┌─ @BeforeStep # Drupal\DrupalExtension\Context\MinkContext::beforeJavascriptStep()
    │
    ╳  Unable to complete AJAX request. {"name":"step.before","feature":"Media","step":"I press \"\u4fdd\u5b58\"","suite":"default"} (RuntimeException)
    │             
```

I'm running `drupal-extension 4.1` with drupal 8.9.3.  My `behat.yml` looks like this:

```
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\RawDrupalContext
        - FailAid\Context\FailureContext
    Drupal\MinkExtension:
      # https://github.com/jhedstrom/drupalextension/issues/486
      ajax_timeout: 30
      # Default configuration has this commented out so it can be overridden.
      base_url: http://MYSITE.lndo.site/
      browser_name: chrome
      # For file uploads.
      files_path: /app/web/sites/default/files/behat
      sessions:
        default:
          goutte:
            guzzle_parameters:
              verify: false
        javascript:
          selenium2:
            wd_host: http://seleniumchromedriver:4444/wd/hub
```

I tried searching the MinkContext for a beforeJavaScript() step but could not find one.

**Comment by nbhimani** [comment]
I am running into similar issue for following statements:

Statement 1: simple submit button with AJAX action
```
When I press the "SUBMIT" button
│
    ╳  Unable to complete AJAX request. {"name":"XXXX","feature":"XXXX","step":"XXXX","suite":"XXXX"} (RuntimeException)
    │
    └─ @AfterStep # Drupal\DrupalExtension\Context\MinkContext::afterJavascriptStep()
```

Statement 2: which opens a browser alert confirming that user is navigating to different site (Ok and Cancel)
```
When I click "LINK"
│
        ╳  unexpected alert open: {Alert text }
        │
        └─ @AfterStep # Drupal\DrupalExtension\Context\MinkContext::afterJavascriptStep()
```

These statements works just fine if I downgrade to drupal/drupal-extension to version 3.4

I have also noticed that drupal/drupal-driver is effected with these versions
drupal/drupal-extension: ^4.1 requires drupal/drupal-driver: ^2
drupal/drupal-extension: ^3.4 requires drupal/drupal-driver: ^1

Please fix these issues soon as possible since I would like to use this updated version with Drupal 9.

Thank you!

**Comment by xurizaemon** [comment]
@ptmkenny here that [beforeJavascriptStep](https://github.com/jhedstrom/drupalextension/search?q=beforeJavascriptStep)

BTW `files_path` there is the source directory for your test uploads, eg if you have a sample image in `/app/tests/behat/resources/sample-image.png`, you can set:

```yaml
  extensions:
    Drupal\MinkExtension:
      files_path: '%paths.base%/resources'
```
and then use it like

`Then I attach the file "sample-image.png" to "Add file"`

This directory is not the destination directory for your uploads, which is what the configuration snippet you've posted has. (Also that config snippet is missing the `extensions:` key?)
