### ISSUE TITLE
base_url port stripped off, causes cURL error

### ISSUE THREAD

**Issue by ronaldroe** [jhedstrom/drupalextension#575]
When I run `/vendor/bin/behat`, it strips off the port, which causes cURL to throw the following error when Mink tries to connect to the site:
```
cURL error 6: Could not resolve host: mesonet.docker.localhost (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) (GuzzleHttp\Exception\ConnectException)
```

I was able to find a suggestion to add the following to the Goutte settings in behat.yml, but it didn't help:
```
        guzzle_parameters:
          curl.options:
            CURLOPT_PORT: 8000
```

I'm at a bit of a loss, because everything else I see about using ports other than 80 just has the port at the end of base_url.

My current behat.yml:
```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Drupal\MinkExtension:
      goutte: ~
      selenium2: ~
      base_url: http://mesonet.docker.localhost:8000
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: "drupal"
      region_map:
        station_selector: "#station-selector"
        station_dropdown: "edit-mesonet-station--RHGIeDz_59w"
```
