### ISSUE TITLE
Error when disabling subcontexts: "Drupal::$container is not initialized yet"

### ISSUE THREAD

**Issue by pfrenssen** [jhedstrom/drupalextension#576]
Subcontexts have been deprecated in #518 and are planned to be removed in #549 

In the current development version of BDE subcontexts are still autoloaded, but this can be disabled as follows:

```yml
default:
  extensions:
    Drupal\DrupalExtension:
      subcontexts:
        autoload: false
        paths: []
```

However this removes the only way that Drupal is automatically bootstrapped at the start of a test suite. This is currently happening in `Drupal\DrupalExtension\Context\Environment\Reader\Reader::findSubContextClasses()` which calls `$driver->getSubDriverPaths()` which calls `$this->bootstrap()`.

If the subcontext autoloading is disabled Drupal is no longer bootstrapped and this leads to this error:

> \Drupal::$container is not initialized yet. \Drupal::setContainer() must be called with a real container. (Drupal\Core\DependencyInjection\ContainerNotInitializedException)
