### ISSUE TITLE
Login breaks if multiple login button exists on the page

### ISSUE THREAD

**Issue by golddragon007** [jhedstrom/drupalextension#604]
The following code finds the wrong log-in button if there is multiple one, therefore later on the tests fails with "The selected node does not have a form ancestor." error.
https://github.com/jhedstrom/drupalextension/blob/master/src/Drupal/DrupalExtension/Manager/DrupalAuthenticationManager.php#L67

It would be nice when the login button is looked for, it looks for one that at least has the same parent container in some level up and not the first fount one.

**Comment by pfrenssen** [comment]
Since this is the only place where we use the `log_in` string, you can try to put the CSS ID of the log in button instead of the text.

```
default:
  extensions:
    Drupal\DrupalExtension:
      text:
        # The CSS ID of the log in button.
        log_in: 'edit-submit'
```

If this is not feasible you can also try to override the `DrupalAuthenticationManager` class with your own customized version. Then you can put custom logic in it to pinpoint the login button.
