### ISSUE TITLE
Nothing happens ...

### ISSUE THREAD

**Issue by ghost** [jhedstrom/drupalextension#7]
Hi, sorry for this rather empty support request - I am a little new to this.

When I run with the blackbox driver everything appears to work as expected except many steps are unavailable such as:

```
# ~/Sites/mysite.localhost $ bin/behat --profile=default --tags="test"
  @test
  Scenario: Lets test this                                      # features/tests.feature:6
    Given I am logged in as a user with the "member admin" role # Drupal\DrupalExtension\Context\DrupalContext::iAmLoggedInWithRole()
      No ability to create users in Drupal\Driver\BlackboxDriver

1 scenario (1 failed)
1 step (1 failed)
0m0.102s
# ~/Sites/mysite.localhost $ 
```

So I'd like to use the Drupal7 driver.  I've created a drupal 7 profile in my composer.json (see below) but when I run the command there is not output at all, no errors, nothing (I've tried with and without the tags filer) ...

```
  drupal7:
    filters:
      tags: "@api"
    extensions:
      Behat\MinkExtension\Extension:
        base_url: http://mysite.localhost:8082
      Drupal\DrupalExtension\Extension:
        api_driver: "drupal"
        drupal:
          # Change this to the absolute path to Drupal install.
          drupal_root: "/Users/me/Sites/mysite.localhost/docroot"
        region_map:
          left sidebar: "#sidebar-first"
          content: "#content"
```

```
  # ~/Sites/mysite.localhost $ bin/behat --profile=drupal7
  # ~/Sites/mysite.localhost $ 
```

Kind regards,

John
