### ISSUE TITLE
Cannot login with new user

### ISSUE THREAD

**Issue by claudiu-cristea** [jhedstrom/drupalextension#99]
My files based on docs:
behat.yml

```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
      base_url: http://local.dev
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drupal:
        drupal_root: /var/www/html
```

features/bootstrap/FeatureContext.php

```
class FeatureContext extends RawDrupalContext implements SnippetAcceptingContext {
  public function __construct() {
  }
}
```

features/test.feature

```
  @api
  Scenario: Test a logged in user.
    Given users:
    | name  | mail              | status | role |
    | behat | behat@example.com | 1      | authenticated user |
    When I am logged in as "behat"
    And I go to /track
    Then I should see "History"
```

This fails with:

```
  @api
  Scenario: Test a logged in user. # features/test.feature:11
    Given users:                   # Drupal\DrupalExtension\Context\DrupalContext::createUsers()
      | name  | mail              | status | role               |
      | behat | behat@example.com | 1      | authenticated user |
    When I am logged in as "behat" # Drupal\DrupalExtension\Context\DrupalContext::assertLoggedInByName()
      Failed to log in as user 'behat' with role 'authenticated user' (Exception)
    And I go to /track
    Then I should see "History"    # Drupal\DrupalExtension\Context\MinkContext::assertPageContainsText()

--- Failed scenarios:

    features/test.feature:11

2 scenarios (1 passed, 1 failed)
7 steps (4 passed, 1 failed, 1 undefined, 1 skipped)
0m1.84s (39.89Mb)
```
